name: ijzershop
display_name: Thema voor ijzershop webshops
version: 1.0.1
author:
  name: "Ijzershop"
  email: "jelmer@ijzershop.nl"
  url: "https://ijzershop.nl"
meta:
  compatibility:
      from: 1.7.0.0
      to: ~
  hooks:
    custom_hooks:
       - name: kiyohBanner
         title: kiyohBanner
         description: Adds kiyoh block
assets:
    css:
      all:
        - id: theme-core-style
          path: assets/theme-core-bundled.css
          media: all
          priority: 1
    js:
      all:
        - id: theme-core-js
          path: assets/js/theme-core.js
          priority: 1
          position: bottom