_combinations:
    resource: 'combination.yml'
    prefix: /products/

admin_products_v2_create:
  path: /create
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:create
    _legacy_controller: AdminProducts
    _legacy_link:
      - AdminProducts:addproduct
      - AdminProducts:add

admin_products_v2_edit:
  path: /{productId}/edit
  methods: [GET, POST, PATCH]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:edit
    _legacy_controller: AdminProducts
    _legacy_link:
      - AdminProducts:updateproduct
      - AdminProducts:update
    _legacy_parameters:
      id_product: productId
  requirements:
    productId: \d+

admin_products_v2_get_images:
    path: /{productId}/getImages
    methods: [GET]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:getImages
        _legacy_controller: AdminProducts
        _legacy_link:
            - AdminProducts:getimages
        _legacy_parameters:
            id_product: productId
    options:
        expose: true
    requirements:
        productId: \d+

admin_products_v2_add_image:
    path: /{productId}/addImage
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:addImage
        _legacy_controller: AdminProducts
        _legacy_link:
            - AdminProducts:addimage
        _legacy_parameters:
            id_product: productId
    options:
        expose: true
    requirements:
        productId: \d+
