imports:
  - { resource: builder.yml }
  - { resource: service.yml }
  - { resource: repository.yml }
  - { resource: context.yml }
  - { resource: factory.yml }
  - { resource: presenter.yml }
  - { resource: validator.yml }
  - { resource: command.yml }
  - { resource: provider.yml }
  - { resource: adapter.yml }
  - { resource: handler.yml }
  - { resource: grid.yml }
  - { resource: segment.yml }
  - { resource: verification.yml }
  - { resource: payment_option_provider.yml }
  - { resource: decoder.yml }

services:
  mollie:
    class: 'Mollie'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mollie'

  Mollie\Install\Installer:
    arguments:
      - '@mollie'
      - '@Mollie\Service\OrderStateImageService'
      - '@Mollie\Install\DatabaseTableInstaller'
      - '@Mollie\Tracker\Segment'

  Mollie\Install\Uninstall:
    arguments:
      - '@Mollie\Install\DatabaseTableUninstaller'
      - '@Mollie\Repository\OrderStateRepository'
      - '@Mollie\Tracker\Segment'

  Mollie\Install\DatabaseTableInstaller:

  Mollie\Install\DatabaseTableUninstaller:

  mollie.adapter.context:
    class: Mollie\Adapter\LegacyContext

  Mollie\Config\Env:
    class: Mollie\Config\Env
