services:
  Mollie\Provider\CreditCardLogoProvider:
    arguments:
      - '@=service("mollie.factory.module_factory").getLocalPath()'
      - '@=service("mollie.factory.module_factory").getPathUri()'
