services:
  Mollie\Validator\OrderConfMailValidator:
    class: Mollie\Validator\OrderConfMailValidator
    arguments:
      - '@Mollie\Adapter\ConfigurationAdapter'

  Mollie\Validator\NewOrderMailValidator:
    class: Mollie\Validator\NewOrderMailValidator
    arguments:
      - '@Mollie\Adapter\ConfigurationAdapter'

  Mollie\Validator\VoucherValidator:
    arguments:
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Service\VoucherService'

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\BasePaymentMethodRestrictionValidator:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\BasePaymentMethodRestrictionValidator
    arguments:
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\PaymentMethod\PaymentMethodCurrencyProvider'
      - '@Mollie\Service\OrderTotal\OrderTotalService'
      - '@Mollie\Provider\OrderTotalProvider'
    tags:
      - { name: mollie.paymentmethodrestriction, priority: 10}

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\ApplePayPaymentMethodRestrictionValidator:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\ApplePayPaymentMethodRestrictionValidator
    arguments:
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Adapter\ConfigurationAdapter'
    tags:
      - { name: mollie.paymentmethodrestriction }

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\KlarnaSliceItPaymentMethodRestrictionValidator:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\KlarnaSliceItPaymentMethodRestrictionValidator
    arguments:
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\PaymentMethod\PaymentMethodCountryProvider'
    tags:
      - { name: mollie.paymentmethodrestriction }

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\KlarnaPayLaterPaymentMethodRestrictionValidator:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\KlarnaPayLaterPaymentMethodRestrictionValidator
    arguments:
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\PaymentMethod\PaymentMethodCountryProvider'
    tags:
      - { name: mollie.paymentmethodrestriction }

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\VoucherPaymentMethodRestrictionValidator:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\VoucherPaymentMethodRestrictionValidator
    arguments:
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Validator\VoucherValidator'
    tags:
      - { name: mollie.paymentmethodrestriction }

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\EnvironmentVersionSpecificPaymentMethodRestrictionValidator:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation\EnvironmentVersionSpecificPaymentMethodRestrictionValidator
    arguments:
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\EnvironmentVersionProvider'
      - '@Mollie\Repository\MethodCountryRepository'
    tags:
      - { name: mollie.paymentmethodrestriction, priority: 9}

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation:
    class: Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation
    arguments:
      - !tagged mollie.paymentmethodrestriction

  Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidationInterface: '@Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation'

  Mollie\Provider\OrderTotalProvider:
    class: Mollie\Provider\OrderTotalProvider
    arguments:
      - '@=service("mollie.adapter.context")'