services:
  Mollie\Validator\OrderConfMailValidator:

  Mollie\Validator\NewOrderMailValidator:

  Mollie\Validator\VoucherValidator:
    arguments:
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Service\VoucherService'
