services:
  _defaults:
    public: true

  modernesmid.core.form.identifiable_object.builder.customer_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
    arguments:
      - 'PrestaShopBundle\Form\Admin\Sell\Customer\CustomerType'
      - '@prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider'


  modernesmid.adapter.customer.query_handler.get_customer_for_editing:
    class: 'MsThemeConfig\Adapter\Customer\QueryHandler\GetCustomerForEditingHandler'
    tags:
      - name: tactician.handler
        command: 'MsThemeConfig\Core\Domain\Customer\Query\GetCustomerForEditing'


  modernesmid.core.form.identifiable_object.handler.customer_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@modernesmid.core.form.identifiable_object.data_handler.customer_form_data_handler'


  modernesmid.core.form.identifiable_object.data_handler.customer_form_data_handler:
    class: 'MsThemeConfig\Core\Form\IdentifiableObject\DataHandler\CustomerFormDataHandler'
    arguments:
      - '@prestashop.core.command_bus'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'
      - '@=service("prestashop.core.b2b.b2b_feature").isActive()'

  prestashop.adapter.customer.command_handler.edit_customer_handler:
    class: 'MsThemeConfig\Adapter\Customer\CommandHandler\EditCustomerHandler'
    arguments:
      - '@prestashop.core.crypto.hashing'
      - '@=service("prestashop.adapter.legacy.configuration").get("_COOKIE_KEY_")'
    tags:
      - name: tactician.handler
        command: 'MsThemeConfig\Core\Domain\Customer\Command\EditCustomerCommand'

  prestashop.adapter.customer.command_handler.add_customer_handler:
    class: 'MsThemeConfig\Adapter\Customer\CommandHandler\AddCustomerHandler'
    arguments:
      - '@prestashop.core.crypto.hashing'
      - '@=service("prestashop.adapter.legacy.configuration").get("_COOKIE_KEY_")'
    tags:
      - name: tactician.handler
        command: 'MsThemeConfig\Core\Domain\Customer\Command\AddCustomerCommand'
