language: php

addons:
    chrome: stable
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.2

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=disabled
  matrix:
    - PRESTASHOP_TEST_TYPE=lint
    - PRESTASHOP_TEST_TYPE=unit
    - PRESTASHOP_TEST_TYPE=e2e

matrix:
  include:
    - php: 7.1
      env: EXTRA_TESTS=functional PRESTASHOP_TEST_TYPE=e2e

before_install:
  # Apache & php-fpm configuration
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh

  # PrestaShop configuration
  - cp tests/parameters.yml.travis app/config/parameters.yml


notifications:
  hipchat: ec4e21c5eb82066ba8be5fd1afefde@1184657

script:
  - composer install --prefer-dist --no-interaction --no-progress
  - bash travis-scripts/install-prestashop
  - if [ $PRESTASHOP_TEST_TYPE = "lint" ]; then
        bash tests/check_file_syntax.sh;
    fi

  - if [ $PRESTASHOP_TEST_TYPE = "unit" ]; then
        composer run-script phpunit-legacy --timeout=0;
    fi
  - if [ $PRESTASHOP_TEST_TYPE = "unit" ]; then
        composer run-script phpunit-admin --timeout=0;
    fi
  - if [ $PRESTASHOP_TEST_TYPE = "unit" ]; then
        composer run-script phpunit-sf --timeout=0;
    fi
  - if [ $PRESTASHOP_TEST_TYPE = "unit" ]; then
        composer run-script phpunit-controllers --timeout=0;
    fi

  # run-functional-tests must run before starter theme
  - if [ $PRESTASHOP_TEST_TYPE = "e2e" ]; then
        bash travis-scripts/run-selenium-tests;
    fi
  - if [ $PRESTASHOP_TEST_TYPE = "e2e" ]; then
        bash travis-scripts/run-functional-tests;
    fi
  - if [ $PRESTASHOP_TEST_TYPE = "e2e" ]; then
        bash travis-scripts/test-startertheme;
    fi

after_script:
  - sudo cat /var/log/apache2/error.log

after_failure:
  - curl -L http://localhost/
  - cat /etc/apache2/envvars
  - cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/php-fpm.log
  - sudo ls -l /var/log/apache2
  - sudo cat /var/log/apache2/other_vhosts_access.log
  - bash ./travis-scripts/base64-screenshots # As we cannot upload file, we display the base64 encoded content of the screenshots
  - cat $TRAVIS_BUILD_DIR/var/log/dev.log
