<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'carrier_options_provider' shared service.

return $this->services['carrier_options_provider'] = new \Mollie\Subscription\Form\ChoiceProvider\CarrierOptionsProvider(($this->services['Mollie'] ?? $this->load('getMollieService.php')));
