<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.form.identifiable_object.handler.price_list_upload_form_handler' shared service.

return $this->services['modernesmid.module.pricemodifier.form.identifiable_object.handler.price_list_upload_form_handler'] = ($this->services['prestashop.core.form.identifiable_object.handler.form_handler_factory'] ?? $this->load('getPrestashop_Core_Form_IdentifiableObject_Handler_FormHandlerFactoryService.php'))->create(($this->services['modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_list_upload_form_data_handler'] ?? $this->load('getModernesmid_Module_Pricemodifier_Form_IdentifiableObject_DataHandler_PriceListUploadFormDataHandlerService.php')));
