<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.grid.factory.price_modifications' shared service.

return $this->services['modernesmid.module.pricemodifier.grid.factory.price_modifications'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['modernesmid.module.pricemodifier.grid.definition.factory.price_modifications'] ?? $this->load('getModernesmid_Module_Pricemodifier_Grid_Definition_Factory_PriceModificationsService.php')), ($this->services['modernesmid.module.pricemodifier.grid.data_provider.price_modifications'] ?? $this->load('getModernesmid_Module_Pricemodifier_Grid_DataProvider_PriceModificationsService.php')), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));
