<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.price_modifications.generator' shared service.

return $this->services['modernesmid.module.pricemodifier.price_modifications.generator'] = new \Modernesmid\Module\Pricemodifier\Database\PriceModificationGenerator(($this->services['modernesmid.module.pricemodifier.repository.price_modification_repository'] ?? $this->load('getModernesmid_Module_Pricemodifier_Repository_PriceModificationRepositoryService.php')), ($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService()), ($this->services['prestashop.core.admin.shop.repository'] ?? $this->load('getPrestashop_Core_Admin_Shop_RepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
