<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.form.identifiable_object.data_provider.offer_integrations_form_data_provider' shared service.

return $this->services['modernesmid.form.identifiable_object.data_provider.offer_integrations_form_data_provider'] = new \MsThemeConfig\Core\Form\OfferIntegrationFormDataProvider(($this->services['modernesmid.repository.offer_integrations_repository'] ?? $this->load('getModernesmid_Repository_OfferIntegrationsRepositoryService.php')));
