<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.adapter.address.command_handler.add_customer_address_handler' shared service.

return $this->services['modernesmid.adapter.address.command_handler.add_customer_address_handler'] = new \MsThemeConfig\Adapter\Address\CommandHandler\AddCustomerAddressHandler();
