<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.adapter.customer.query_handler.get_customer_for_editing' shared service.

return $this->services['modernesmid.adapter.customer.query_handler.get_customer_for_editing'] = new \MsThemeConfig\Adapter\Customer\QueryHandler\GetCustomerForEditingHandler();
