<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.form.identifiable_object.data_provider.price_modification_form_data_provider' shared service.

return $this->services['modernesmid.module.pricemodifier.form.identifiable_object.data_provider.price_modification_form_data_provider'] = new \Modernesmid\Module\Pricemodifier\Form\PriceModificationFormDataProvider(($this->services['modernesmid.module.pricemodifier.repository.price_modification_repository'] ?? $this->load('getModernesmid_Module_Pricemodifier_Repository_PriceModificationRepositoryService.php')));
