<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_modification_form_data_handler' shared service.

return $this->services['modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_modification_form_data_handler'] = new \Modernesmid\Module\Pricemodifier\Form\PriceModificationFormDataHandler(($this->services['modernesmid.module.pricemodifier.repository.price_modification_repository'] ?? $this->load('getModernesmid_Module_Pricemodifier_Repository_PriceModificationRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
