<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.form.identifiable_object.data_handler.offer_integrations_form_data_handler' shared service.

return $this->services['modernesmid.form.identifiable_object.data_handler.offer_integrations_form_data_handler'] = new \MsThemeConfig\Core\Form\OfferIntegrationFormDataHandler(($this->services['modernesmid.repository.offer_integrations_repository'] ?? $this->load('getModernesmid_Repository_OfferIntegrationsRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
