<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.grid.definition.factory.price_modifications' shared service.

$this->services['modernesmid.module.pricemodifier.grid.definition.factory.price_modifications'] = $instance = new \Modernesmid\Module\Pricemodifier\Grid\Definition\Factory\PriceModificationGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php'))->generate("admin_common_reset_search", ["controller" => "price_modification", "action" => "index"]), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php'))->generate("modernesmid_pricemodifier_price_modification_index"));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
