<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.grid.definition.factory.offer_integration' shared service.

$this->services['modernesmid.grid.definition.factory.offer_integration'] = $instance = new \MsThemeConfig\Core\Grid\Definition\Factory\OfferIntegrationGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))->getCurrentRequest(), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php'))->generate("offerintegration_index"), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php'))->generate("admin_common_reset_search", ["controller" => "admin_offer", "action" => "index"]));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
