<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.price_modifications.install' shared service.

return $this->services['modernesmid.module.pricemodifier.price_modifications.install'] = new \Modernesmid\Module\Pricemodifier\Database\PriceModificationInstaller(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps176_');
