<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.price_modifications.domain.price_modification.command_handler.toggle_is_active_price_modification_handler' shared service.

return $this->services['modernesmid.module.pricemodifier.price_modifications.domain.price_modification.command_handler.toggle_is_active_price_modification_handler'] = new \Modernesmid\Module\Pricemodifier\Domain\PriceModification\CommandHandler\ToggleIsActivePriceModificationHandler(($this->services['modernesmid.module.pricemodifier.repository.price_modification_repository'] ?? $this->load('getModernesmid_Module_Pricemodifier_Repository_PriceModificationRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
