<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.grid.data_provider.offer_integrations' shared service.

return $this->services['modernesmid.grid.data_provider.offer_integrations'] = new \MsThemeConfig\Core\Grid\Definition\Data\OfferIntegrationDataFactory(($this->services['modernesmid.grid.query_builder.offer_integration'] ?? $this->load('getModernesmid_Grid_QueryBuilder_OfferIntegrationService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.core.grid.query.doctrine_query_parser'] ?? ($this->services['prestashop.core.grid.query.doctrine_query_parser'] = new \PrestaShop\PrestaShop\Core\Grid\Query\DoctrineQueryParser())), 'oi_offer');
