<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.grid.factory.offer_integrations' shared service.

return $this->services['modernesmid.grid.factory.offer_integrations'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['modernesmid.grid.definition.factory.offer_integration'] ?? $this->load('getModernesmid_Grid_Definition_Factory_OfferIntegrationService.php')), ($this->services['modernesmid.grid.data_provider.offer_integrations'] ?? $this->load('getModernesmid_Grid_DataProvider_OfferIntegrationsService.php')), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));
