<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.form.identifiable_object.builder.price_list_upload_form_builder' shared service.

return $this->services['modernesmid.module.pricemodifier.form.identifiable_object.builder.price_list_upload_form_builder'] = ($this->services['prestashop.core.form.builder.form_builder_factory'] ?? $this->load('getPrestashop_Core_Form_Builder_FormBuilderFactoryService.php'))->create('Modernesmid\\Module\\Pricemodifier\\Form\\PriceListUploadType', ($this->services['modernesmid.module.pricemodifier.form.identifiable_object.data_provider.price_modification_form_data_provider'] ?? $this->load('getModernesmid_Module_Pricemodifier_Form_IdentifiableObject_DataProvider_PriceModificationFormDataProviderService.php')));
