<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.form.identifiable_object.builder.offer_integrations_form_builder' shared service.

return $this->services['modernesmid.form.identifiable_object.builder.offer_integrations_form_builder'] = ($this->services['prestashop.core.form.builder.form_builder_factory'] ?? $this->load('getPrestashop_Core_Form_Builder_FormBuilderFactoryService.php'))->create('MsThemeConfig\\Core\\Form\\OfferIntegrationType', ($this->services['modernesmid.form.identifiable_object.data_provider.offer_integrations_form_data_provider'] ?? $this->load('getModernesmid_Form_IdentifiableObject_DataProvider_OfferIntegrationsFormDataProviderService.php')));
