<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mollie.PsAccountsInstaller' shared service.

return $this->services['Mollie.PsAccountsInstaller'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('5.0');
