<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'modernesmid.module.pricemodifier.grid.data_provider.price_modifications' shared service.

return $this->services['modernesmid.module.pricemodifier.grid.data_provider.price_modifications'] = new \Modernesmid\Module\Pricemodifier\Grid\Definition\Data\PriceModificationDataFactory(($this->services['modernesmid.module.pricemodifier.grid.query_builder.price_modification'] ?? $this->load('getModernesmid_Module_Pricemodifier_Grid_QueryBuilder_PriceModificationService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.core.grid.query.doctrine_query_parser'] ?? ($this->services['prestashop.core.grid.query.doctrine_query_parser'] = new \PrestaShop\PrestaShop\Core\Grid\Query\DoctrineQueryParser())), 'price_modification');
