<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.adapter.order.query_handler.get_order_preview_handler' shared service.

return $this->privates['prestashop.adapter.order.query_handler.get_order_preview_handler'] = new \MsThemeConfig\Service\DmsAdminOrderPreviewService(($this->services['PrestaShop\\PrestaShop\\Core\\Localization\\Locale\\Repository'] ?? $this->getRepositoryService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->getLocale(), ($this->services['prestashop.adapter.address.formatter'] ?? ($this->services['prestashop.adapter.address.formatter'] = new \PrestaShop\PrestaShop\Adapter\Address\AddressFormatter())));
