<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pricemodifier.demo' shared service.

return $this->services['pricemodifier.demo'] = new \PrestaShop\Module\Pricemodifier\Admin\ConfigurationController(($this->services['doctrine.cache.provider'] ?? $this->getDoctrine_Cache_ProviderService()));
