<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'subscription_options_data_provider' shared service.

return $this->services['subscription_options_data_provider'] = new \Mollie\Subscription\Form\Options\SubscriptionOptionsDataProvider(($this->services['subscription_options_configuration'] ?? $this->load('getSubscriptionOptionsConfigurationService.php')));
