<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mollie\Subscription\Grid\SubscriptionGridDefinitionFactory' shared service.

$this->services['Mollie\\Subscription\\Grid\\SubscriptionGridDefinitionFactory'] = $instance = new \Mollie\Subscription\Grid\SubscriptionGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['Mollie'] ?? $this->load('getMollieService.php')), ($this->services['Mollie\\Subscription\\Grid\\Accessibility\\SubscriptionCancelAccessibility'] ?? ($this->services['Mollie\\Subscription\\Grid\\Accessibility\\SubscriptionCancelAccessibility'] = new \Mollie\Subscription\Grid\Accessibility\SubscriptionCancelAccessibility())));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
