<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'subscription_options_type' shared service.

return $this->services['subscription_options_type'] = new \Mollie\Subscription\Form\Options\SubscriptionOptionsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['carrier_options_provider'] ?? $this->load('getCarrierOptionsProviderService.php')), ($this->services['Mollie'] ?? $this->load('getMollieService.php')));
