<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mollie\Subscription\Grid\Accessibility\SubscriptionCancelAccessibility' shared service.

return $this->services['Mollie\\Subscription\\Grid\\Accessibility\\SubscriptionCancelAccessibility'] = new \Mollie\Subscription\Grid\Accessibility\SubscriptionCancelAccessibility();
