<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'subscription_grid_factory' shared service.

return $this->services['subscription_grid_factory'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['Mollie\\Subscription\\Grid\\SubscriptionGridDefinitionFactory'] ?? $this->load('getSubscriptionGridDefinitionFactoryService.php')), ($this->services['subscription_grid_data_factory'] ?? $this->load('getSubscriptionGridDataFactoryService.php')), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));
