<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'subscription_options_form_handler_deprecated' shared service.

return $this->services['subscription_options_form_handler_deprecated'] = new \PrestaShop\PrestaShop\Core\Form\FormHandler(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'))->createBuilder(), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['subscription_options_data_provider'] ?? $this->load('getSubscriptionOptionsDataProviderService.php')), ['subscription_options' => 'Mollie\\Subscription\\Form\\Options\\SubscriptionOptionsType'], 'SubscriptionOptions');
