<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuD2s85HUIYEvCOOvSF9Y'."\n".'To0oaaqyLjdmypyId+UwCqCv1IEONRMNxxxQI5H9YgkiknZR0lIJflU8QxrturLF'."\n".'fFgxKVRwAxhTp8mgubKOJ3+jgwt+Q9ZQiZy/mTUD6woyV4b5wZifE0JdPf9rOrx0'."\n".'4T5fw4NJ9Z7aTUB+CzIuC5kdIAoJlnbO5XMvfgj37xgafRnxJJKTfsF4BvlNw2Bg'."\n".'/nyLlIZLDgbtgWSgI682xem25KgI3sS4DMElm2/CoHAuCERwDhX7I0EhcDq22Cuc'."\n".'ItjMWHTupc24Ez7ZNnf9G0yqSAaOrKSEP+5ut1/O21M1NPfDeE50/pqLGQwPaNFB'."\n".'rwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
