admin_international_translation_overview:
    path:     /
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle:Admin/Translations:overview

admin_international_translations_list:
    path: /list
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Translations:list
        _legacy_controller: AdminTranslations
    requirements:
        locale: \w+

admin_international_translations_module:
    path: /module
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Translations:module
    requirements:
        locale: \w+

admin_international_translations_export_theme:
    path: /export
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Translations:exportTheme
        _legacy_controller: AdminTranslations

# Localization routes

admin_localization_show_settings:
    path: /localization
    methods: [GET]
    defaults:
        _controller: PrestaShopBundle:Admin\Improve\International\Localization:showSettings
        _legacy_controller: AdminLocalization

admin_localization_save_settings:
    path: /localization
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Improve\International\Localization:processForm
        _legacy_controller: AdminLocalization

admin_localization_import_pack:
    path: /localization/import_pack
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Improve\International\Localization:importLocalizationPack
        _legacy_controller: AdminLocalization
