admin_carts_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:index
    _legacy_controller: AdminCarts

admin_carts_view:
  path: /{cartId}/view
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:view
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+

admin_carts_info:
  path: /info
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:getInfo
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_create_empty:
  path: /create-empty
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:createEmpty
    _legacy_controller: AdminCarts
  requirements:
    customerId: \d+
  options:
    expose: true

admin_carts_duplicate:
  path: /duplicate
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:duplicateOrderCart
    _legacy_controller: AdminCarts
  requirements:
    orderId: \d+
  options:
    expose: true

admin_carts_edit_address:
  path: /edit-address
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:editAddress
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true
