admin_carts_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:index
    _legacy_controller: AdminCarts

admin_carts_view:
  path: /{cartId}/view
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:view
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+

admin_carts_load_cart:
  path: /load
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:loadCart
    _legacy_controller: AdminCarts
  requirements:
    customerId: \d+

admin_carts_edit_address:
  path: /edit-address
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:editAddress
    _legacy_controller: AdminCarts
    requirements:
      cartId: \d+
