admin_email:
    path: /
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:index'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails

admin_email_search:
    path: /
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:search'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails:search

admin_email_process:
    path: /settings
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:processForm'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails:update

admin_send_test_email:
    path: /send-testing-email
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:processTestEmailSending'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails:testEmail
    condition: 'request.isXmlHttpRequest()'

admin_delete_selected_email_logs:
    path: /delete/selected
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:processDeleteSelectedEmailLogs'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails:submitBulkdeletemail

admin_delete_all_email_logs:
    path: /delete/all
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:processDeleteAllEmailLogs'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails:deleteAll

admin_delete_single_email_log:
    path: /delete/{mailId}
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Email:processSingleEmailLog'
        _legacy_controller: AdminEmails
        _legacy_link: AdminEmails:deletemail
        _legacy_parameters:
            id_mail: mailId
    requirements:
        mailId: \d+
