admin_webservice:
    path: /
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:index'
        _legacy_controller: AdminWebservice

admin_webservice_search:
  path: /
  methods: POST
  defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:search'
        _legacy_controller: AdminWebservice

admin_webservice_save:
    path: /settings
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:processForm'
        _legacy_controller: AdminWebservice

admin_delete_single_webservice_log:
    path: /delete/{webserviceAccountId}
    methods: DELETE
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:deleteSingleWebservice'

admin_webservice_status_toggle:
    path: /status/{idWebserviceAccount}
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:toggleStatus'
