admin_webservice:
    path: /
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:index'
        _legacy_controller: AdminWebservice

admin_webservice_search:
  path: /
  methods: POST
  defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:search'
        _legacy_controller: AdminWebservice

admin_webservice_save:
    path: /settings
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:processForm'
        _legacy_controller: AdminWebservice

admin_delete_single_webservice_log:
    path: /delete/{webserviceAccountId}
    methods: DELETE
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:deleteSingleWebservice'

admin_delete_multiple_webservice_log:
    path: /delete
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:deleteMultipleWebservice'

admin_webservice_status_toggle:
    path: /status/{idWebserviceAccount}
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:toggleStatus'

admin_webservice_bulk_enable:
    path: /status/bulk/enable
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:enableMultipleStatus'

admin_webservice_bulk_disable:
  path: /status/bulk/disable
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Webservice:disableMultipleStatus'
