parameters:
    AdapterSecurityAdminClass:                LegacyTests\PrestaShopBundle\Mock\AdapterSecurityAdminMock
    prestashop.security.voter.product.class:  LegacyTests\PrestaShopBundle\Mock\PageVoter

imports:
    - { resource: config_dev.yml }
    - { resource: "../../tests/Resources/config/services.yml" }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: '%use_debug_toolbar%'
    intercept_redirects: true

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                dbname: "test_%database_name%"
    orm:
        metadata_cache_driver: "array"
        query_cache_driver: "array"
