export type IconFamily = "classic" | "sharp" | "duotone";
export type IconPrefix = "fas" | "far" | "fal" | "fat" | "fad" | "fab" | "fak" | "fass" | "fasr" | "fasl" ;
export type CssStyleClass = "fa-solid" | "fa-regular" | "fa-light" | "fa-thin" | "fa-duotone" | "fa-brands" ;
export type IconStyle = "solid" | "regular" | "light" | "thin" | "duotone" | "brands" ;
export type IconPathData = string | string[]

export interface IconLookup {
  prefix: IconPrefix;
  // IconName is defined in the code that will be generated at build time and bundled with this file.
  iconName: IconName;
}

export interface IconDefinition extends IconLookup {
  icon: [
    number, // width
    number, // height
    string[], // ligatures
    string, // unicode
    IconPathData // svgPathData
  ];
}

export interface IconPack {
  [key: string]: IconDefinition;
}

export type IconName = 'google' | 
  'facebook' | 
  'whatsapp' | 
  'twitter' | 
  '0' | 
  '1' | 
  '2' | 
  '3' | 
  '4' | 
  '5' | 
  '6' | 
  '7' | 
  '8' | 
  '9' | 
  'at' | 
  'info' | 
  'sliders-up' | 
  'sliders-v' | 
  'scissors' | 
  'cut' | 
  'list' | 
  'list-squares' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'eye-slash' | 
  'chevron-up' | 
  'money-bill' | 
  'badge-percent' | 
  'user' | 
  'key' | 
  'person-dolly' | 
  'ban' | 
  'cancel' | 
  'star' | 
  'pallet-boxes' | 
  'palette-boxes' | 
  'pallet-alt' | 
  '00' | 
  'forklift' | 
  'dolly' | 
  'dolly-box' | 
  'user-tie' | 
  'boxes-packing' | 
  'arrows-left-right' | 
  'arrows-h' | 
  'pallet-box' | 
  'square' | 
  'heart' | 
  'truck-clock' | 
  'shipping-timed' | 
  'circle-question' | 
  'question-circle' | 
  'cart-flatbed' | 
  'dolly-flatbed' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'phone' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'envelope-open-dollar' | 
  'table-cells' | 
  'th' | 
  'file-pdf' | 
  'table-cells-large' | 
  'th-large' | 
  'location-exclamation' | 
  'map-marker-exclamation' | 
  'tag' | 
  'ellipsis-stroke-vertical' | 
  'ellipsis-v-alt' | 
  'comment' | 
  'envelope' | 
  'circle-info' | 
  'info-circle' | 
  'truck' | 
  'minus' | 
  'subtract' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'list-radio' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'thumbs-down' | 
  'location-dot' | 
  'map-marker-alt' | 
  'magnifying-glass' | 
  'search' | 
  'cart-flatbed-empty' | 
  'dolly-flatbed-empty' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'truck-fast' | 
  'shipping-fast' | 
  'star-sharp' | 
  'cart-shopping-fast' | 
  'sidebar' | 
  'square-phone' | 
  'phone-square' | 
  'plus' | 
  'add' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'chevron-left' | 
  'chevron-right' | 
  'percent' | 
  'percentage' | 
  'conveyor-belt' | 
  'rotate' | 
  'sync-alt' | 
  'warehouse' | 
  'qrcode' | 
  'table-list' | 
  'th-list' | 
  'check' | 
  'cart-flatbed-boxes' | 
  'dolly-flatbed-alt' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'scanner-gun' | 
  'scanner' | 
  'arrows-up-down' | 
  'arrows-v' | 
  'thumbs-up' | 
  'square-full' | 
  'barcode' | 
  'notdef' | 
  '0' | 
  '1' | 
  '2' | 
  '3' | 
  '4' | 
  '5' | 
  '6' | 
  '7' | 
  '8' | 
  '9' | 
  'at' | 
  'info' | 
  'sliders-up' | 
  'sliders-v' | 
  'scissors' | 
  'cut' | 
  'list' | 
  'list-squares' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'eye-slash' | 
  'chevron-up' | 
  'money-bill' | 
  'badge-percent' | 
  'user' | 
  'key' | 
  'person-dolly' | 
  'ban' | 
  'cancel' | 
  'star' | 
  'pallet-boxes' | 
  'palette-boxes' | 
  'pallet-alt' | 
  '00' | 
  'forklift' | 
  'dolly' | 
  'dolly-box' | 
  'user-tie' | 
  'boxes-packing' | 
  'arrows-left-right' | 
  'arrows-h' | 
  'pallet-box' | 
  'square' | 
  'heart' | 
  'truck-clock' | 
  'shipping-timed' | 
  'circle-question' | 
  'question-circle' | 
  'cart-flatbed' | 
  'dolly-flatbed' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'phone' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'envelope-open-dollar' | 
  'table-cells' | 
  'th' | 
  'file-pdf' | 
  'table-cells-large' | 
  'th-large' | 
  'location-exclamation' | 
  'map-marker-exclamation' | 
  'tag' | 
  'ellipsis-stroke-vertical' | 
  'ellipsis-v-alt' | 
  'comment' | 
  'envelope' | 
  'circle-info' | 
  'info-circle' | 
  'truck' | 
  'minus' | 
  'subtract' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'list-radio' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'thumbs-down' | 
  'location-dot' | 
  'map-marker-alt' | 
  'magnifying-glass' | 
  'search' | 
  'cart-flatbed-empty' | 
  'dolly-flatbed-empty' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'truck-fast' | 
  'shipping-fast' | 
  'star-sharp' | 
  'cart-shopping-fast' | 
  'sidebar' | 
  'square-phone' | 
  'phone-square' | 
  'plus' | 
  'add' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'chevron-left' | 
  'chevron-right' | 
  'percent' | 
  'percentage' | 
  'conveyor-belt' | 
  'rotate' | 
  'sync-alt' | 
  'warehouse' | 
  'qrcode' | 
  'table-list' | 
  'th-list' | 
  'check' | 
  'cart-flatbed-boxes' | 
  'dolly-flatbed-alt' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'scanner-gun' | 
  'scanner' | 
  'arrows-up-down' | 
  'arrows-v' | 
  'thumbs-up' | 
  'square-full' | 
  'barcode' | 
  'notdef' | 
  '0' | 
  '1' | 
  '2' | 
  '3' | 
  '4' | 
  '5' | 
  '6' | 
  '7' | 
  '8' | 
  '9' | 
  'at' | 
  'info' | 
  'sliders-up' | 
  'sliders-v' | 
  'scissors' | 
  'cut' | 
  'list' | 
  'list-squares' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'eye-slash' | 
  'chevron-up' | 
  'money-bill' | 
  'badge-percent' | 
  'user' | 
  'key' | 
  'person-dolly' | 
  'ban' | 
  'cancel' | 
  'star' | 
  'pallet-boxes' | 
  'palette-boxes' | 
  'pallet-alt' | 
  '00' | 
  'forklift' | 
  'dolly' | 
  'dolly-box' | 
  'user-tie' | 
  'boxes-packing' | 
  'arrows-left-right' | 
  'arrows-h' | 
  'pallet-box' | 
  'square' | 
  'heart' | 
  'truck-clock' | 
  'shipping-timed' | 
  'circle-question' | 
  'question-circle' | 
  'cart-flatbed' | 
  'dolly-flatbed' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'phone' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'envelope-open-dollar' | 
  'table-cells' | 
  'th' | 
  'file-pdf' | 
  'table-cells-large' | 
  'th-large' | 
  'location-exclamation' | 
  'map-marker-exclamation' | 
  'tag' | 
  'ellipsis-stroke-vertical' | 
  'ellipsis-v-alt' | 
  'comment' | 
  'envelope' | 
  'circle-info' | 
  'info-circle' | 
  'truck' | 
  'minus' | 
  'subtract' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'list-radio' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'thumbs-down' | 
  'location-dot' | 
  'map-marker-alt' | 
  'magnifying-glass' | 
  'search' | 
  'cart-flatbed-empty' | 
  'dolly-flatbed-empty' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'truck-fast' | 
  'shipping-fast' | 
  'star-sharp' | 
  'cart-shopping-fast' | 
  'sidebar' | 
  'square-phone' | 
  'phone-square' | 
  'plus' | 
  'add' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'chevron-left' | 
  'chevron-right' | 
  'percent' | 
  'percentage' | 
  'conveyor-belt' | 
  'rotate' | 
  'sync-alt' | 
  'warehouse' | 
  'qrcode' | 
  'table-list' | 
  'th-list' | 
  'check' | 
  'cart-flatbed-boxes' | 
  'dolly-flatbed-alt' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'scanner-gun' | 
  'scanner' | 
  'arrows-up-down' | 
  'arrows-v' | 
  'thumbs-up' | 
  'square-full' | 
  'barcode' | 
  'notdef' | 
  '0' | 
  '1' | 
  '2' | 
  '3' | 
  '4' | 
  '5' | 
  '6' | 
  '7' | 
  '8' | 
  '9' | 
  'at' | 
  'info' | 
  'sliders-up' | 
  'sliders-v' | 
  'scissors' | 
  'cut' | 
  'list' | 
  'list-squares' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'eye-slash' | 
  'chevron-up' | 
  'money-bill' | 
  'badge-percent' | 
  'user' | 
  'key' | 
  'person-dolly' | 
  'ban' | 
  'cancel' | 
  'star' | 
  'pallet-boxes' | 
  'palette-boxes' | 
  'pallet-alt' | 
  '00' | 
  'forklift' | 
  'dolly' | 
  'dolly-box' | 
  'user-tie' | 
  'boxes-packing' | 
  'arrows-left-right' | 
  'arrows-h' | 
  'pallet-box' | 
  'square' | 
  'heart' | 
  'truck-clock' | 
  'shipping-timed' | 
  'circle-question' | 
  'question-circle' | 
  'cart-flatbed' | 
  'dolly-flatbed' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'phone' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'envelope-open-dollar' | 
  'table-cells' | 
  'th' | 
  'file-pdf' | 
  'table-cells-large' | 
  'th-large' | 
  'location-exclamation' | 
  'map-marker-exclamation' | 
  'tag' | 
  'ellipsis-stroke-vertical' | 
  'ellipsis-v-alt' | 
  'comment' | 
  'envelope' | 
  'circle-info' | 
  'info-circle' | 
  'truck' | 
  'minus' | 
  'subtract' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'list-radio' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'thumbs-down' | 
  'location-dot' | 
  'map-marker-alt' | 
  'magnifying-glass' | 
  'search' | 
  'cart-flatbed-empty' | 
  'dolly-flatbed-empty' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'truck-fast' | 
  'shipping-fast' | 
  'star-sharp' | 
  'cart-shopping-fast' | 
  'sidebar' | 
  'square-phone' | 
  'phone-square' | 
  'plus' | 
  'add' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'chevron-left' | 
  'chevron-right' | 
  'percent' | 
  'percentage' | 
  'conveyor-belt' | 
  'rotate' | 
  'sync-alt' | 
  'warehouse' | 
  'qrcode' | 
  'table-list' | 
  'th-list' | 
  'check' | 
  'cart-flatbed-boxes' | 
  'dolly-flatbed-alt' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'scanner-gun' | 
  'scanner' | 
  'arrows-up-down' | 
  'arrows-v' | 
  'thumbs-up' | 
  'square-full' | 
  'barcode' | 
  'notdef';
