version: '2.1'

volumes:
  db-data:
  vendor:
  var:
  temp-ps:

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psreference
    restart: always
  reference-release:
    container_name: prestashop_autoupgrade
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VERSION: $VERSION
        BASE_VERSION: $BASE_VERSION
    volumes:
      - ./:/var/www/html/modules/autoupgrade
      - temp-ps:/var/www/html # Used for another container which needs PrestaShop content
    environment:
      DISABLE_MAKE: 0
      PS_INSTALL_AUTO: 1
      DB_SERVER: mysql
      DB_PASSWD: root
      DB_NAME: psreference
      PS_DOMAIN: localhost:8001
      PS_INSTALL_DB: 1
      PS_ERASE_DB: 1
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
      PS_LANGUAGE: en
      PS_COUNTRY: fr
      PS_DEV_MODE: 0
    depends_on:
      - mysql
    ports:
      - '8001:80'
