admin_mail_theme_send_test_mail:
  path: /send-test-mail/{locale}/{theme}/{layout}
  methods: [GET]
  defaults:
    _controller: 'ModerneSmidMailTheme\Controller\DmsMailThemeController::sendTestMailAction'
    _legacy_link: AdminMailTheme:rawModuleLayout
    _legacy_controller: AdminMailTheme
    module: ''
#
#admin_mail_theme_send_test_module_mail:
#  path: /send-test-mail/{locale}/{theme}/{module}/{layout}
#  methods: [GET]
#  defaults:
#    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:sendTestMail
#    _legacy_link: AdminMailTheme:rawModuleLayout
#    _legacy_controller: AdminMailTheme
