# main services
imports:
  - { resource: ./common.yml }

services:
  _defaults:
    public: true
  # Form services
  modernesmid.module.pricemodifier.type.price_modification:
    class: 'Modernesmid\Module\Pricemodifier\Form\PriceModificationType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  modernesmid.module.pricemodifier.form.identifiable_object.data_provider.price_modification_form_data_provider:
    class: 'Modernesmid\Module\Pricemodifier\Form\PriceModificationFormDataProvider'
    arguments:
      - '@modernesmid.module.pricemodifier.repository.price_modification_repository'

  modernesmid.module.pricemodifier.form.identifiable_object.builder.price_modification_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Modernesmid\Module\Pricemodifier\Form\PriceModificationType'
      - '@modernesmid.module.pricemodifier.form.identifiable_object.data_provider.price_modification_form_data_provider'

  modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_modification_form_data_handler:
    class: 'Modernesmid\Module\Pricemodifier\Form\PriceModificationFormDataHandler'
    arguments:
      - '@modernesmid.module.pricemodifier.repository.price_modification_repository'
      - '@doctrine.orm.default_entity_manager'

  modernesmid.module.pricemodifier.form.identifiable_object.handler.price_modification_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_modification_form_data_handler'

  modernesmid.module.pricemodifier.form.identifiable_object.builder.price_list_upload_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Modernesmid\Module\Pricemodifier\Form\PriceListUploadType'
      - '@modernesmid.module.pricemodifier.form.identifiable_object.data_provider.price_modification_form_data_provider'

  modernesmid.module.pricemodifier.form.identifiable_object.handler.price_list_upload_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_list_upload_form_data_handler'

  modernesmid.module.pricemodifier.form.identifiable_object.data_handler.price_list_upload_form_data_handler:
    class: 'Modernesmid\Module\Pricemodifier\Form\PriceListUploadFormDataHandler'
    arguments:
      - '@modernesmid.module.pricemodifier.repository.price_modification_repository'
      - '@doctrine.orm.default_entity_manager'


  # Grid services
  modernesmid.module.pricemodifier.grid.definition.factory.price_modifications:
    class: 'Modernesmid\Module\Pricemodifier\Grid\Definition\Factory\PriceModificationGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true
    arguments:
      - "@=service('router').generate('admin_common_reset_search', {'controller': 'price_modification', 'action': 'index'})"
      - "@=service('router').generate('modernesmid_pricemodifier_price_modification_index')"

  modernesmid.module.pricemodifier.grid.query_builder.price_modification:
    class: 'Modernesmid\Module\Pricemodifier\Grid\Query\PriceModificationQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"

  modernesmid.module.pricemodifier.grid.factory.price_modifications:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
    - '@modernesmid.module.pricemodifier.grid.definition.factory.price_modifications' # our definition factory
    - '@modernesmid.module.pricemodifier.grid.data_provider.price_modifications'
    - '@prestashop.core.grid.filter.form_factory'                            # core service needed by grid factory
    - '@prestashop.core.hook.dispatcher'                           # core service needed by grid factory

  modernesmid.module.pricemodifier.grid.data_provider.price_modifications:
    class: 'Modernesmid\Module\Pricemodifier\Grid\Definition\Data\PriceModificationDataFactory'
    arguments:
      - '@modernesmid.module.pricemodifier.grid.query_builder.price_modification'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'price_modification'



















  # Generator service
  modernesmid.module.pricemodifier.price_modifications.generator:
    class: 'Modernesmid\Module\Pricemodifier\Database\PriceModificationGenerator'
    arguments:
      - '@modernesmid.module.pricemodifier.repository.price_modification_repository'
      - '@prestashop.core.admin.lang.repository'
      - '@prestashop.core.admin.shop.repository'
      - '@doctrine.orm.default_entity_manager'

  # CQRS pattern toggle status
  modernesmid.module.pricemodifier.price_modifications.domain.price_modification.query_handler.get_price_modification_is_active_price_modification_handler:
    class: 'Modernesmid\Module\Pricemodifier\Domain\PriceModification\QueryHandler\GetPriceModificationIsActiveHandler'
    arguments:
      - '@modernesmid.module.pricemodifier.repository.price_modification_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: 'Modernesmid\Module\Pricemodifier\Domain\PriceModification\Query\GetPriceModificationIsActive'

  modernesmid.module.pricemodifier.price_modifications.domain.price_modification.command_handler.toggle_is_active_price_modification_handler:
    class: 'Modernesmid\Module\Pricemodifier\Domain\PriceModification\CommandHandler\ToggleIsActivePriceModificationHandler'
    arguments:
      - '@modernesmid.module.pricemodifier.repository.price_modification_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: 'Modernesmid\Module\Pricemodifier\Domain\PriceModification\Command\ToggleIsActivePriceModificationCommand'
