var lang = {
    addNew: "Nieuw toevoegen",
    after: "Na",
    alignment: "Uitlijning",
    altText: "Alt-tekst",
    alwaysResponsive: "Altijd responsief",
    badgepill: "Badge-pil",
    before: "Voor",
    bodyHtml: "Body-HTML",
    border: "Rand",
    bordered: "Met rand",
    borderless: "Randloos",
    bottom: "Onder",
    browse: "Bladeren",
    button: "Knop",
    buttonSize: "Knopgrootte",
    buttonStyle: "Knopstijl",
    cancel: "Annuleren",
    caption: "Bijschrift",
    cardStyle: "Kaartstijl",
    cells: "Cellen",
    center: "Midden",
    choose: "Kiezen",
    closeButton: "Sluitknop",
    code: "Code",
    container: "Container",
    current: "Huidig",
    custom: "Aangepast",
    customColor: "Kies een kleur",
    customSize: "Aangepaste grootte",
    dark: "Donker",
    default: "Standaard",
    disabled: "Uitgeschakeld",
    disabledWarning: "Uitgeschakelde elementen zijn niet bewerkbaar in de TinyMCE-editor",
    dismissable: "Sluitbaar",
    flip: "Spiegelen",
    flipBoth: "Beide spiegelen",
    flipHorizontal: "Horizontaal spiegelen",
    flipVertical: "Verticaal spiegelen",
    floatLeft: "Links zweven",
    floatRight: "Rechts zweven",
    fluidContainer: "Vloeibare container (breedte 100%)",
    footer: "Voettekst",
    footerHtml: "Voettekst-HTML",
    header: "Koptekst",
    headerHtml: "Koptekst-HTML",
    horizontalHeader: "Horizontale koptekst",
    icon: "Pictogram",
    iconColor: "Pictogramkleur",
    icons: "Pictogrammen",
    iconSize: "Pictogramgrootte",
    iconStyle: "Pictogramstijl",
    image: "Afbeelding",
    imageOverlay: "Afbeeldingsoverlay",
    imageOverlayHtml: "Afbeeldingsoverlay-HTML",
    imageStyle: "Afbeeldingsstijl",
    inputWarning: "Pictogrammen zijn niet beschikbaar bij <em>input</em>-tags",
    insert: "Invoegen",
    insertAfterContainer: "Invoegen na de huidige container",
    insertAfterRow: "Invoegen na de huidige rij",
    insertBeforeContainer: "Invoegen vóór de huidige container",
    insertBeforeRow: "Invoegen vóór de huidige rij",
    insertBeginning: "Invoegen aan het begin van het document",
    insertBeginningContainer: "Invoegen aan het begin van de huidige container",
    insertCursorPosition: "Invoegen op de cursorpositie",
    insertEnd: "Invoegen aan het einde van het document",
    insertEndContainer: "Invoegen aan het einde van de huidige container",
    items: "Items",
    large: "Groot",
    largeRadius: "Grote radius",
    left: "Links",
    light: "Licht",
    link: "Link",
    medium: "Medium",
    mediumRadius: "Middelgrote radius",
    no: "Nee",
    noContainer: "Geen container",
    normalContainer: "Normale container",
    options: "Opties",
    others: "Overig",
    outline: "Omlijning",
    page: "Pagina",
    pages: "Pagina's",
    paginationfirst: "Eerste",
    paginationlast: "Laatste",
    position: "Positie",
    preview: "Voorbeeld",
    pulse: "Puls",
    removeImage: "Afbeelding verwijderen",
    reset: "Reset",
    responsive: "Responsief",
    responsiveLg: "Responsief op grote en XL-schermen",
    responsiveMd: "Responsief op medium en grotere schermen",
    responsiveSm: "Responsief op kleine en grotere schermen",
    responsiveXl: "Responsief op XL-schermen",
    right: "Rechts",
    rotate: "Roteren",
    roundedCircle: "Afgeronde cirkel",
    roundedPill: "Afgeronde pil",
    rowsCols: "Rijen / Kolommen",
    size: "Grootte",
    small: "Klein",
    smallRadius: "Kleine radius",
    snippets: "Snippets",
    spin: "Draaien",
    structure: "Structuur",
    style: "Stijl",
    submit: "Verzenden",
    tableDark: "Tabel donker",
    tableEditDisabledInfo: "Het bewerken van de tabelstructuur is uitgeschakeld. Rijen en kolommen kunnen direct in TinyMCE worden bewerkt.",
    tableHover: "Tabel hover",
    tableSmall: "Tabel klein",
    tableStriped: "Gestreepte tabel",
    tag: "Tag",
    templates: "Sjablonen",
    text: "Tekst",
    textAlignment: "Tekstuitlijning",
    textColor: "Tekstkleur",
    thumbnail: "Miniatuur",
    top: "Boven",
    verticalHeader: "Verticale koptekst",
    width: "Breedte",
    yes: "Ja"
}
