tinymce.addI18n("nl", {
    "Add col after": "Kolom na toevoegen",
    "Add col before": "Kolom vóór toevoegen",
    "Add paragraph after": "Alinea na toevoegen",
    "Add paragraph at beginning container": "Alinea aan begin van de huidige container toevoegen",
    "Add paragraph at beginning": "Alinea aan het begin van het document toevoegen",
    "Add paragraph at end container": "Alinea aan het einde van de huidige container toevoegen",
    "Add paragraph at end": "Alinea aan het einde van het document toevoegen",
    "Add paragraph before": "Alinea vóór toevoegen",
    "Add row after": "Rij na toevoegen",
    "Add row before": "Rij vóór toevoegen",
    "Alert": "Melding",
    "Badge": "Badge",
    "Bootstrap Elements": "Bootstrap-elementen",
    "Breadcrumb": "Kruimelpad",
    "Button": "Knop",
    "Cancel": "Annuleren",
    "Card": "Kaart",
    "column": "kolom",
    "columns": "kolommen",
    "Default": "Standaard",
    "Disable Template Edition": "Sjabloonbewerking uitschakelen",
    "Edit col": "Kolom bewerken",
    "Edit row": "Rij bewerken",
    "Enable Template Edition": "Sjabloonbewerking inschakelen",
    "Hide Modal": "Modal verbergen",
    "Icon": "Pictogram",
    "Image": "Afbeelding",
    "Insert/Edit Bootstrap Alert": "Bootstrap-melding invoegen/bewerken",
    "Insert/Edit Bootstrap Badge": "Bootstrap-badge invoegen/bewerken",
    "Insert/Edit Bootstrap Breadcrumb": "Bootstrap-kruimelpad invoegen/bewerken",
    "Insert/Edit Bootstrap Button": "Bootstrap-knop invoegen/bewerken",
    "Insert/Edit Bootstrap Card": "Bootstrap-kaart invoegen/bewerken",
    "Insert/Edit Bootstrap Icon": "Bootstrap-pictogram invoegen/bewerken",
    "Insert/Edit Bootstrap Image": "Bootstrap-afbeelding invoegen/bewerken",
    "Insert/Edit Bootstrap Pager": "Bootstrap-pager invoegen/bewerken",
    "Insert/Edit Bootstrap Pagination": "Bootstrap-paginering invoegen/bewerken",
    "Insert/Edit Bootstrap Table": "Bootstrap-tabel invoegen/bewerken",
    "Insert/Edit Bootstrap Template": "Bootstrap-sjabloon invoegen/bewerken",
    "Insert/Edit Snippet": "Snippet invoegen/bewerken",
    "Label": "Label",
    "New column": "Nieuwe kolom",
    "New paragraph": "Nieuwe alinea",
    "OK": "OK",
    "Pager": "Pager",
    "Pagination": "Paginering",
    "Remove col": "Kolom verwijderen",
    "Remove row": "Rij verwijderen",
    "Screens": "Schermen",
    "Show Modal": "Modal tonen",
    "Snippet": "Snippet",
    "Table": "Tabel",
    "Template": "Sjabloon"
});
