var lang = {
    addNew: "Adicionar novo",
    after: "Depois",
    alignment: "Alinhamento",
    altText: "Texto alternativo",
    alwaysResponsive: "Sempre responsivo",
    badgepill: "Badge pílula",
    before: "Antes",
    bodyHtml: "Body HTML",
    border: "Borda",
    bordered: "Com bordas",
    borderless: "Sem borda",
    bottom: "Final",
    browse: "Browse",
    button: "Botão",
    buttonSize: "Tamanho do botão",
    buttonStyle: "Estilo do botão",
    cancel: "Cancelar",
    caption: "Legenda",
    cardStyle: "Estilo do Card",
    cells: "células",
    center: "Centro",
    choose: "Escolher",
    closeButton: "botão fechar",
    code: "código",
    container: "Container",
    current: "Atual",
    custom: "Customizado",
    customColor: "Escolha uma cor",
    customSize: "Tamanho customizado",
    dark: "Escuro",
    default: "Padrão",
    disabled: "Desabilitado",
    disabledWarning: "Elementos desabilitados não poderão ser editados",
    dismissable: "Pode ser fechado",
    flip: "Girar",
    flipBoth: "Girar ambos",
    flipHorizontal: "Girar horizontal",
    flipVertical: "Girar vertical",
    floatLeft: "Flutuar na esquerda",
    floatRight: "Flutuar na direita",
    fluidContainer: "Container fluido (largura 100%)",
    footer: "Rodapé",
    footerHtml: "Rodapé HTML",
    header: "Cabeçalho",
    headerHtml: "Cabeçalho HTML",
    horizontalHeader: "Cabeçalho horizontal",
    icon: "ícone",
    iconColor: "Cor do ícone",
    icons: "ícones",
    iconSize: "Tamhno do ícone",
    iconStyle: "Estilo do ícone",
    image: "Imagem",
    imageOverlay: "Sobreposição da imagem",
    imageOverlayHtml: "Sobreposição da imagem HTML",
    imageStyle: "Estilo da imagem",
    inputWarning: "ícones não estão disponívels em tags <em>input</em>",
    insert: "Inserir",
    insertAfterContainer: "Inserir depois do container selecionado",
    insertAfterRow: "Inserir depois da linha selecionada",
    insertBeforeContainer: "Inserir antes do container selecionado",
    insertBeforeRow: "Inserir antes da linha selecionada",
    insertBeginning: "Inserir no começo do documento",
    insertBeginningContainer: "Inserir no começo do container selecionado",
    insertCursorPosition: "Inserir na posição do cursor",
    insertEnd: "Inserir no final do documento",
    insertEndContainer: "Inserir no final do container selecionado",
    items: "Itens",
    large: "Grande",
    largeRadius: "Raio grande",
    left: "Esquerda",
    light: "Claro",
    link: "Link",
    medium: "Médio",
    mediumRadius: "Raio médio",
    no: "Não",
    noContainer: "Sem container",
    normalContainer: "Container normal",
    options: "Opções",
    others: "Outros",
    outline: "Outline",
    page: "Página",
    pages: "Páginas",
    paginationfirst: "Primeiro",
    paginationlast: "Último",
    position: "Posição",
    preview: "Pré-visualização",
    pulse: "Pulso",
    removeImage: "Remover imagem",
    reset: "Reset",
    responsive: "Responsive",
    responsiveLg: "Responsivo em telas grandes e extragrandes",
    responsiveMd: "Responsivo em telas mídias ou maiores",
    responsiveSm: "Responsivo em telas pequenas ou maiores",
    responsiveXl: "Responsivo em telas extragrandes",
    right: "Direita",
    rotate: "Girar",
    roundedCircle: "Círculo",
    roundedPill: "Pílula redonda",
    rowsCols: "Linhas/Colunas",
    size: "Tamanho",
    small: "Pequeno",
    smallRadius: "Raio pequeno",
    snippets: "Snippets",
    spin: "Girar",
    structure: "Estrutura",
    style: "Estilo",
    submit: "Submeter",
    tableEditDisabledInfo: "A modificação da estrutura da mesa está desativada. Linhas e colunas podem ser editadas diretamente no TinyMce",
    tableHover: "Hover na tabela",
    tableSmall: "Tabela pequena",
    tableStriped: "Tabela listrada",
    tag: "Tag",
    templates: "Templates",
    text: "Texto",
    textAlignment: "Alinhamento do texto",
    textColor: "Cor do texto",
    thumbnail: "Miniatura",
    top: "Topo",
    verticalHeader: "Cabeçalho vertical",
    width: "Largura",
    yes: "Sim"
}
