var bootstrapUiI18n = {
    "Add col after": "Adicionar coluna depois",
    "Add col before": "Adicionar coluna antes",
    "Add paragraph after": "Adicionar um parágrafo após",
    "Add paragraph at beginning container": "Acrescentar um parágrafo no início do recipiente selecionado",
    "Add paragraph at beginning": "Acrescentar um parágrafo no início do documento",
    "Add paragraph at end container": "Adicionar parágrafo no final do container selecionado",
    "Add paragraph at end": "Adicionar parágrafo no final do documento",
    "Add paragraph before": "Adicionar parágrafo antes",
    "Add row after": "Adicionar linha depois",
    "Add row before": "Adicionar linha antes",
    "Alert": "Alerta",
    "Badge": "Badge",
    "Bootstrap Elements": "Bootstrap Elements",
    "Breadcrumb": "Breadcrumb",
    "Button": "Botão",
    "Cancel": "Cancelar",
    "Card": "Card",
    "column": "Coluna",
    "columns": "Colunas",
    "Default": "Padrão",
    "Disable Template Edition": "Desabilitar Edição de template",
    "Edit col": "Editar coluna",
    "Edit row": "Editar linha",
    "Enable Template Edition": "Habilitar Edição de template",
    "Hide Modal": "Esconder modal",
    "Icon": "Icone",
    "Image": "Imagem",
    "Insert/Edit Bootstrap Alert": "Inserir/Editar Alerta do Bootstrap",
    "Insert/Edit Bootstrap Badge": "Inserir/Editar Badge do Bootstrap",
    "Insert/Edit Bootstrap Breadcrumb": "Inserir/Editar Breadcrumb do Bootstrap",
    "Insert/Edit Bootstrap Button": "Inserir/Editar Botão do Bootstrap",
    "Insert/Edit Bootstrap Card": "Inserir/Editar Card do Bootstrap",
    "Insert/Edit Bootstrap Icon": "Inserir/Editar ícone do Bootstrap",
    "Insert/Edit Bootstrap Image": "Inserir/Editar Imagem do Bootstrap",
    "Insert/Edit Bootstrap Pager": "Inserir/Editar Bootstrap Pager",
    "Insert/Edit Bootstrap Pagination": "Inserir/Editar Bootstrap Pagination",
    "Insert/Edit Bootstrap Table": "Inserir/Editar Tabela do Bootstrap",
    "Insert/Edit Bootstrap Template": "Inserir/Editar Template do Bootstrap",
    "Insert/Edit Snippet": "Inserir/Editar Snippet",
    "Label": "Label",
    "New column": "Nova coluna",
    "New paragraph": "Novo parágrafo",
    "OK": "OK",
    "Pager": "Pager",
    "Pagination": "Paginação",
    "Remove col": "Remover coluna",
    "Remove row": "Remover linha",
    "Screens": "Telas",
    "Show Modal": "Mostrar Modal",
    "Snippet": "Snippet",
    "Table": "Tabela",
    "Template": "Template"
};
