#All the module related routes

admin_module_catalog:
    path:     /catalog
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::catalogAction
        
admin_module_catalog_search:
    path:     /catalog/search/{keyword}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::catalogAction

admin_module_import:
    path:     /import
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::importAction
