admin_system_information:
    path: system_information
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle\Controller\Admin\AdvancedParameters\SystemInformationController::indexAction'
        _legacy_controller: AdminInformation

admin_system_information_check_files:
    path: system_information/files
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle\Controller\Admin\AdvancedParameters\SystemInformationController::displayCheckFilesAction'
        _legacy_controller: AdminInformation
    condition: "request.isXmlHttpRequest()"