<?php
// This file provides legacy class aliases for IDEs.
// Generated from var/cache/dev/class_index.php.
if (false) {
    abstract class AbstractAssetManager extends AbstractAssetManagerCore {}
    abstract class AbstractCheckoutStep extends AbstractCheckoutStepCore {}
    abstract class AbstractForm extends AbstractFormCore {}
    abstract class AbstractLogger extends AbstractLoggerCore {}
    class Access extends AccessCore {}
    class AddressChecksum extends AddressChecksumCore {}
    class AddressController extends AddressControllerCore {}
    class AddressValidator extends AddressValidatorCore {}
    class AddressesController extends AddressesControllerCore {}
    class AdminAccessController extends AdminAccessControllerCore {}
    class AdminCarrierWizardController extends AdminCarrierWizardControllerCore {}
    class AdminCarriersController extends AdminCarriersControllerCore {}
    class AdminCartRulesController extends AdminCartRulesControllerCore {}
    class AdminCountriesController extends AdminCountriesControllerCore {}
    class AdminCustomerThreadsController extends AdminCustomerThreadsControllerCore {}
    class AdminDashboardController extends AdminDashboardControllerCore {}
    class AdminGroupsController extends AdminGroupsControllerCore {}
    class AdminImportController extends AdminImportControllerCore {}
    class AdminModulesPositionsController extends AdminModulesPositionsControllerCore {}
    class AdminNotFoundController extends AdminNotFoundControllerCore {}
    class AdminPdfController extends AdminPdfControllerCore {}
    class AdminQuickAccessesController extends AdminQuickAccessesControllerCore {}
    class AdminReturnController extends AdminReturnControllerCore {}
    class AdminSearchConfController extends AdminSearchConfControllerCore {}
    class AdminSearchController extends AdminSearchControllerCore {}
    class AdminShopController extends AdminShopControllerCore {}
    class AdminShopGroupController extends AdminShopGroupControllerCore {}
    class AdminShopUrlController extends AdminShopUrlControllerCore {}
    class AdminSpecificPriceRuleController extends AdminSpecificPriceRuleControllerCore {}
    class AdminStatsController extends AdminStatsControllerCore {}
    abstract class AdminStatsTabController extends AdminStatsTabControllerCore {}
    class AdminStoresController extends AdminStoresControllerCore {}
    class AdminTabsController extends AdminTabsControllerCore {}
    class AdminTagsController extends AdminTagsControllerCore {}
    class AdminTaxRulesGroupController extends AdminTaxRulesGroupControllerCore {}
    class AdminTranslationsController extends AdminTranslationsControllerCore {}
    class Alias extends AliasCore {}
    class Attachment extends AttachmentCore {}
    class AttachmentController extends AttachmentControllerCore {}
    class AttributeGroupLang extends AttributeGroupLangCore {}
    class AttributeLang extends AttributeLangCore {}
    class AuthController extends AuthControllerCore {}
    class BestSalesController extends BestSalesControllerCore {}
    class BoOrder extends BoOrderCore {}
    class CMS extends CMSCore {}
    class CMSCategory extends CMSCategoryCore {}
    class CMSRole extends CMSRoleCore {}
    class CSV extends CSVCore {}
    abstract class Cache extends CacheCore {}
    class CacheApc extends CacheApcCore {}
    class CacheMemcache extends CacheMemcacheCore {}
    class CacheMemcached extends CacheMemcachedCore {}
    class CacheXcache extends CacheXcacheCore {}
    class CarrierLang extends CarrierLangCore {}
    abstract class CarrierModule extends CarrierModuleCore {}
    class CartChecksum extends CartChecksumCore {}
    class CartRuleTypeLang extends CartRuleTypeLangCore {}
    class CategoryController extends CategoryControllerCore {}
    class CategoryLang extends CategoryLangCore {}
    class CccReducer extends CccReducerCore {}
    class ChangeCurrencyController extends ChangeCurrencyControllerCore {}
    class Chart extends ChartCore {}
    class CheckoutPaymentStep extends CheckoutPaymentStepCore {}
    class CheckoutPersonalInformationStep extends CheckoutPersonalInformationStepCore {}
    class CheckoutProcess extends CheckoutProcessCore {}
    class CheckoutSession extends CheckoutSessionCore {}
    class CmsCategoryLang extends CmsCategoryLangCore {}
    class Combination extends CombinationCore {}
    class ConditionsToApproveFinder extends ConditionsToApproveFinderCore {}
    class Configuration extends ConfigurationCore {}
    class ConfigurationKPI extends ConfigurationKPICore {}
    class ConfigurationLang extends ConfigurationLangCore {}
    class ConfigurationTest extends ConfigurationTestCore {}
    class Connection extends ConnectionCore {}
    class ConnectionsSource extends ConnectionsSourceCore {}
    class Contact extends ContactCore {}
    class ContactController extends ContactControllerCore {}
    class ContactInformationController extends ContactInformationControllerCore {}
    class ContactLang extends ContactLangCore {}
    class ContactOfferController extends ContactOfferControllerCore {}
    abstract class Controller extends ControllerCore {}
    class Cookie extends CookieCore {}
    class Country extends CountryCore {}
    class CssMinifier extends CssMinifierCore {}
    class Currency extends CurrencyCore {}
    class Curve extends CurveCore {}
    class CustomerAddress extends CustomerAddressCore {}
    class CustomerAddressForm extends CustomerAddressFormCore {}
    class CustomerAddressFormatter extends CustomerAddressFormatterCore {}
    class CustomerAddressPersister extends CustomerAddressPersisterCore {}
    class CustomerLoginFormatter extends CustomerLoginFormatterCore {}
    class CustomerMessage extends CustomerMessageCore {}
    class CustomerSession extends CustomerSessionCore {}
    class CustomerThread extends CustomerThreadCore {}
    class Customization extends CustomizationCore {}
    class CustomizationField extends CustomizationFieldCore {}
    class DataLang extends DataLangCore {}
    class DateRange extends DateRangeCore {}
    abstract class Db extends DbCore {}
    class DbMySQLi extends DbMySQLiCore {}
    class DbPDO extends DbPDOCore {}
    class DbQuery extends DbQueryCore {}
    class Delivery extends DeliveryCore {}
    class DeliveryOptionsFinder extends DeliveryOptionsFinderCore {}
    class DiscountController extends DiscountControllerCore {}
    class Dispatcher extends DispatcherCore {}
    class DummyAdminController extends DummyAdminControllerCore {}
    class Employee extends EmployeeCore {}
    class EmployeeSession extends EmployeeSessionCore {}
    class Feature extends FeatureCore {}
    class FeatureFlag extends FeatureFlagCore {}
    class FeatureLang extends FeatureLangCore {}
    class FeatureValue extends FeatureValueCore {}
    class FeatureValueLang extends FeatureValueLangCore {}
    class FileLogger extends FileLoggerCore {}
    class FormField extends FormFieldCore {}
    class Gender extends GenderCore {}
    class GenderLang extends GenderLangCore {}
    class GetFileController extends GetFileControllerCore {}
    class Group extends GroupCore {}
    class GroupLang extends GroupLangCore {}
    class GroupReduction extends GroupReductionCore {}
    class Guest extends GuestCore {}
    class HTMLTemplateSupplyOrderForm extends HTMLTemplateSupplyOrderFormCore {}
    class Helper extends HelperCore {}
    class HelperCalendar extends HelperCalendarCore {}
    class HelperForm extends HelperFormCore {}
    class HelperImageUploader extends HelperImageUploaderCore {}
    class HelperKpi extends HelperKpiCore {}
    class HelperKpiRow extends HelperKpiRowCore {}
    class HelperList extends HelperListCore {}
    class HelperOptions extends HelperOptionsCore {}
    class HelperShop extends HelperShopCore {}
    class HelperTreeCategories extends HelperTreeCategoriesCore {}
    class HelperTreeShops extends HelperTreeShopsCore {}
    class HelperUploader extends HelperUploaderCore {}
    class HelperView extends HelperViewCore {}
    class HistoryController extends HistoryControllerCore {}
    class Hook extends HookCore {}
    interface ITreeToolbar extends ITreeToolbarCore {}
    interface ITreeToolbarButton extends ITreeToolbarButtonCore {}
    class IdentityController extends IdentityControllerCore {}
    class Image extends ImageCore {}
    class ImageManager extends ImageManagerCore {}
    class ImageType extends ImageTypeCore {}
    class IndexController extends IndexControllerCore {}
    class JavascriptManager extends JavascriptManagerCore {}
    class JsMinifier extends JsMinifierCore {}
    class Language extends LanguageCore {}
    class LinkProxy extends LinkProxyCore {}
    class LocalizationPack extends LocalizationPackCore {}
    class Manufacturer extends ManufacturerCore {}
    class ManufacturerAddress extends ManufacturerAddressCore {}
    class ManufacturerController extends ManufacturerControllerCore {}
    class Media extends MediaCore {}
    class Message extends MessageCore {}
    class Meta extends MetaCore {}
    class MetaLang extends MetaLangCore {}
    abstract class Module extends ModuleCore {}
    abstract class ModuleAdminController extends ModuleAdminControllerCore {}
    class ModuleFrontController extends ModuleFrontControllerCore {}
    abstract class ModuleGraph extends ModuleGraphCore {}
    abstract class ModuleGraphEngine extends ModuleGraphEngineCore {}
    abstract class ModuleGrid extends ModuleGridCore {}
    abstract class ModuleGridEngine extends ModuleGridEngineCore {}
    class MyAccountController extends MyAccountControllerCore {}
    class NewProductsController extends NewProductsControllerCore {}
    class Notification extends NotificationCore {}
    abstract class ObjectModel extends ObjectModelCore {}
    class OrderCartRule extends OrderCartRuleCore {}
    class OrderController extends OrderControllerCore {}
    class OrderDetail extends OrderDetailCore {}
    class OrderFollowController extends OrderFollowControllerCore {}
    class OrderHistory extends OrderHistoryCore {}
    class OrderMessage extends OrderMessageCore {}
    class OrderMessageLang extends OrderMessageLangCore {}
    class OrderPayment extends OrderPaymentCore {}
    class OrderReturn extends OrderReturnCore {}
    class OrderReturnController extends OrderReturnControllerCore {}
    class OrderReturnState extends OrderReturnStateCore {}
    class OrderReturnStateLang extends OrderReturnStateLangCore {}
    class OrderSlip extends OrderSlipCore {}
    class OrderSlipController extends OrderSlipControllerCore {}
    class OrderStateLang extends OrderStateLangCore {}
    class PDF extends PDFCore {}
    class Page extends PageCore {}
    class PageNotFoundController extends PageNotFoundControllerCore {}
    class PasswordController extends PasswordControllerCore {}
    class PaymentOptionsFinder extends PaymentOptionsFinderCore {}
    class PdfInvoiceController extends PdfInvoiceControllerCore {}
    class PdfOrderReturnController extends PdfOrderReturnControllerCore {}
    class PdfOrderSlipController extends PdfOrderSlipControllerCore {}
    class PdfPhysicalOnCreditOrderSlipController extends PdfPhysicalOnCreditOrderSlipControllerCore {}
    class PdfPhysicalOrderSlipController extends PdfPhysicalOrderSlipControllerCore {}
    class PhpEncryption extends PhpEncryptionCore {}
    class PhpEncryptionEngine extends PhpEncryptionEngineCore {}
    class PrestaShopBackup extends PrestaShopBackupCore {}
    class PrestaShopCollection extends PrestaShopCollectionCore {}
    class PrestaShopDatabaseException extends PrestaShopDatabaseExceptionCore {}
    class PrestaShopException extends PrestaShopExceptionCore {}
    class PrestaShopLogger extends PrestaShopLoggerCore {}
    class PrestaShopModuleException extends PrestaShopModuleExceptionCore {}
    class PrestaShopObjectNotFoundException extends PrestaShopObjectNotFoundExceptionCore {}
    class PrestaShopPaymentException extends PrestaShopPaymentExceptionCore {}
    class PricesDropController extends PricesDropControllerCore {}
    class ProductAssembler extends ProductAssemblerCore {}
    class ProductAttribute extends ProductAttributeCore {}
    class ProductDownload extends ProductDownloadCore {}
    class ProductPresenterFactory extends ProductPresenterFactoryCore {}
    abstract class ProductPresentingFrontController extends ProductPresentingFrontControllerCore {}
    class ProductSale extends ProductSaleCore {}
    class ProductSupplier extends ProductSupplierCore {}
    class Profile extends ProfileCore {}
    class ProfileLang extends ProfileLangCore {}
    class QuickAccess extends QuickAccessCore {}
    class QuickAccessLang extends QuickAccessLangCore {}
    class RangePrice extends RangePriceCore {}
    class RangeWeight extends RangeWeightCore {}
    class RegistrationController extends RegistrationControllerCore {}
    class RequestSql extends RequestSqlCore {}
    class Risk extends RiskCore {}
    class RiskLang extends RiskLangCore {}
    class Search extends SearchCore {}
    class SearchController extends SearchControllerCore {}
    class SearchEngine extends SearchEngineCore {}
    class Shop extends ShopCore {}
    class ShopGroup extends ShopGroupCore {}
    class ShopUrl extends ShopUrlCore {}
    class SitemapController extends SitemapControllerCore {}
    class SmartyCustom extends SmartyCustomCore {}
    class SmartyCustomTemplate extends SmartyCustomTemplateCore {}
    class SmartyDevTemplate extends SmartyDevTemplateCore {}
    class SmartyResourceModule extends SmartyResourceModuleCore {}
    class SmartyResourceParent extends SmartyResourceParentCore {}
    class SpecificPrice extends SpecificPriceCore {}
    class SpecificPriceFormatter extends SpecificPriceFormatterCore {}
    class SpecificPriceRule extends SpecificPriceRuleCore {}
    class State extends StateCore {}
    class StatisticsController extends StatisticsControllerCore {}
    class Stock extends StockCore {}
    class StockManager extends StockManagerCore {}
    class StockManagerFactory extends StockManagerFactoryCore {}
    abstract class StockManagerModule extends StockManagerModuleCore {}
    class StockMvt extends StockMvtCore {}
    class StockMvtReason extends StockMvtReasonCore {}
    class StockMvtReasonLang extends StockMvtReasonLangCore {}
    class StockMvtWS extends StockMvtWSCore {}
    class Store extends StoreCore {}
    class StoresController extends StoresControllerCore {}
    class StylesheetManager extends StylesheetManagerCore {}
    class Supplier extends SupplierCore {}
    class SupplierAddress extends SupplierAddressCore {}
    class SupplierController extends SupplierControllerCore {}
    class SupplyOrder extends SupplyOrderCore {}
    class SupplyOrderDetail extends SupplyOrderDetailCore {}
    class SupplyOrderHistory extends SupplyOrderHistoryCore {}
    class SupplyOrderReceiptHistory extends SupplyOrderReceiptHistoryCore {}
    class SupplyOrderState extends SupplyOrderStateCore {}
    class SupplyOrderStateLang extends SupplyOrderStateLangCore {}
    class Tab extends TabCore {}
    class TabLang extends TabLangCore {}
    class Tag extends TagCore {}
    class Tax extends TaxCore {}
    class TaxCalculator extends TaxCalculatorCore {}
    class TaxConfiguration extends TaxConfigurationCore {}
    class TaxManagerFactory extends TaxManagerFactoryCore {}
    abstract class TaxManagerModule extends TaxManagerModuleCore {}
    class TaxRule extends TaxRuleCore {}
    class TaxRulesGroup extends TaxRulesGroupCore {}
    class TaxRulesTaxManager extends TaxRulesTaxManagerCore {}
    class TemplateFinder extends TemplateFinderCore {}
    class ThemeLang extends ThemeLangCore {}
    class Translate extends TranslateCore {}
    class TranslatedConfiguration extends TranslatedConfigurationCore {}
    class Tree extends TreeCore {}
    class TreeToolbar extends TreeToolbarCore {}
    abstract class TreeToolbarButton extends TreeToolbarButtonCore {}
    class TreeToolbarLink extends TreeToolbarLinkCore {}
    class TreeToolbarSearch extends TreeToolbarSearchCore {}
    class TreeToolbarSearchCategories extends TreeToolbarSearchCategoriesCore {}
    class Upgrader extends UpgraderCore {}
    class UploadController extends UploadControllerCore {}
    class Uploader extends UploaderCore {}
    class ValidateConstraintTranslator extends ValidateConstraintTranslatorCore {}
    class Warehouse extends WarehouseCore {}
    class WarehouseAddress extends WarehouseAddressCore {}
    class WarehouseProductLocation extends WarehouseProductLocationCore {}
    class WebserviceException extends WebserviceExceptionCore {}
    class WebserviceKey extends WebserviceKeyCore {}
    class WebserviceOutputBuilder extends WebserviceOutputBuilderCore {}
    class WebserviceOutputJSON extends WebserviceOutputJSONCore {}
    class WebserviceOutputXML extends WebserviceOutputXMLCore {}
    class WebserviceRequest extends WebserviceRequestCore {}
    class WebserviceSpecificManagementAttachments extends WebserviceSpecificManagementAttachmentsCore {}
    class WebserviceSpecificManagementImages extends WebserviceSpecificManagementImagesCore {}
    class WebserviceSpecificManagementSearch extends WebserviceSpecificManagementSearchCore {}
    class Zone extends ZoneCore {}
}
