services:
    # Service aliases for backward campatibility
    prestashop.core.api.stockMovement.repository:
        alias: prestashop.core.api.stock_movement.repository
        deprecated: 'The "%service_id%" service is deprecated. Use "prestashop.core.api.stock_movement.repository" instead'

    prestashop.core.api.stockMovement.controller:
        alias: prestashop.core.api.stock_movement.controller
        deprecated: 'The "%service_id%" service is deprecated. Use "prestashop.core.api.stock_movement.controller" instead'

    prestashop.twig.extension.dataFormatter:
        alias: prestashop.twig.extension.data_formatter
        deprecated: 'The "%service_id%" service is deprecated. Use "prestashop.twig.extension.data_formatter" instead'
