var lang = {
    addNew: "Nieuwe toevoegen",
    after: "Na",
    alignment: "Uitlijnen",
    altText: "Alt tekst",
    alwaysResponsive: "Altijd responsive",
    badgepill: "Badge knop",
    before: "Voor",
    bodyHtml: "Body HTML",
    border: "Rand",
    bordered: "Met rand",
    borderless: "Zonder rand",
    bottom: "Onder",
    browse: "Zoeken/Selecteren",
    button: "Knop",
    buttonSize: "Knop groote",
    buttonStyle: "Knop stijl",
    cancel: "Annuleren",
    caption: "Onderschrift",
    cardStyle: "Kaart stijl",
    cells: "Cellen",
    center: "Midden",
    choose: "Kiezen",
    closeButton: "Sluit knop",
    code: "Code",
    container: "Container",
    current: "Huidige",
    custom: "Aangepast",
    customColor: "Selecteer een kleur",
    customSize: "Aangepast formaat",
    dark: "Donker",
    default: "Standaard",
    disabled: "Uitgeschakeld",
    disabledWarning: "Uitgeschakelde elementen zullen niet beschikbaar zijn in de tiny mce tekst bewerker",
    dismissable: "Annuleerbaar",
    flip: "Spiegelen",
    flipBoth: "Spiegel beide",
    flipHorizontal: "Spiegel horizontaal",
    flipVertical: "Spiegel verticaal",
    floatLeft: "Geforceerd links",
    floatRight: "Geforceerd rechts",
    fluidContainer: "Fluid container (breedte 100%)",
    footer: "Footer",
    footerHtml: "Footer HTML",
    header: "Header",
    headerHtml: "Header HTML",
    horizontalHeader: "Horizontaal header",
    icon: "Icoon",
    iconColor: "Icoon kleur",
    icons: "Iconen",
    iconSize: "Icoon formaat",
    iconStyle: "Icoon stijl",
    image: "Afbeelding",
    imageOverlay: "Afbeelding overlay",
    imageOverlayHtml: "Afbeelding overlay HTML",
    imageStyle: "Afbeelding stijl",
    inputWarning: "Iconen zijn niet beschikbaar met <em>input</em> tags",
    insert: "Invoegen",
    insertAfterContainer: "Voeg in na de huidige container",
    insertAfterRow: "Voeg in na de huidige regel",
    insertBeforeContainer: "Voeg in voor de huidige container",
    insertBeforeRow: "Voeg in voor de huidige regel",
    insertBeginning: "Voeg in aan het begin van het document",
    insertBeginningContainer: "Voeg in aan het begin van de huidige container",
    insertCursorPosition: "Voeg in op de cursor positie",
    insertEnd: "Voeg toe aan het einde van het document",
    insertEndContainer: "Voeg toe aan het einde van de huidige container",
    items: "Items",
    large: "Groot",
    largeRadius: "Grote Ronding",
    left: "Links",
    light: "Licht",
    link: "Link",
    medium: "Middel",
    mediumRadius: "Middel-grote ronding",
    no: "Nee",
    noContainer: "Geen container",
    normalContainer: "Normale container",
    options: "Opties",
    others: "Anderen",
    outline: "Omlijnd",
    page: "Pagina",
    pages: "Pagina's",
    paginationfirst: "Eerste",
    paginationlast: "Laatse",
    position: "Positie",
    preview: "Voorbeeld",
    pulse: "Pulseren",
    removeImage: "Verwijder afbeelding",
    reset: "Resetten",
    responsive: "Schaalbaar",
    responsiveLg: "Schaalbaar op Grote en XL beeldschermen",
    responsiveMd: "Schaalbaar op Middel-grote beeldschermen en groter",
    responsiveSm: "Schaalbaar op Kleine beeldschermen en groter",
    responsiveXl: "Schaalbaar op XL beeldschermen",
    right: "Rechts",
    rotate: "Omdraaien",
    roundedCircle: "Afgeronde circel",
    roundedPill: "Afgeronde ovaal",
    rowsCols: "Rijen / Kollommen",
    size: "Formaat",
    small: "Klein",
    smallRadius: "Kleine ronding",
    snippets: "Snippets",
    spin: "Draaien",
    structure: "Structuur",
    style: "Stijl",
    submit: "Ok",
    tableDark: "Tabel donker",
    tableEditDisabledInfo: "Het wijzigen van de tabel structuur is uitgeschakeld. U kunt rijen en kolommen kunt u direct in de tiny MCE tekst bewerker wijzigen.",
    tableHover: "Tabel hover-effect",
    tableSmall: "Tabel klein",
    tableStriped: "Tabel gestreept",
    tag: "Tag",
    templates: "Templates",
    text: "Tekst",
    textAlignment: "Tekst uitlinen",
    textColor: "Tekst kleur",
    thumbnail: "Thumbnail",
    top: "Bovenin",
    verticalHeader: "Verticale header",
    width: "Breedte",
    yes: "Ja"
}
