services:
    _defaults:
        public: true

    prestashop.core.hook.dispatcher:
        class: 'PrestaShop\PrestaShop\Core\Hook\HookDispatcher'
        arguments:
            - '@prestashop.hook.dispatcher'

    prestashop.core.hook.provider.grid_definition_hook_by_service_ids_provider:
      class: PrestaShop\PrestaShop\Core\Hook\Provider\GridDefinitionHookByServiceIdsProvider
      arguments:
        - '@service_container'

    prestashop.core.hook.provider.identifiable_object_hook_by_form_type_provider:
      class: PrestaShop\PrestaShop\Core\Hook\Provider\IdentifiableObjectHookByFormTypeProvider
      arguments:
        - '@form.factory'

    prestashop.core.hook.generator.dynamic_hook_descriptive_content_generator:
      class: 'PrestaShop\PrestaShop\Core\Hook\Generator\DynamicHookDescriptiveContentGenerator'
      arguments:
        - '':
            'prefix': ''
            'suffix': ''
            'title': 'test'
            'description': 'test'
        - '@prestashop.core.util.string.string_validator'
        - '@prestashop.core.util.string.string_modifier'
