services:
  _defaults:
    public: true

  prestashop.core.news.circuit_breaker.settings:
    class: PrestaShop\CircuitBreaker\FactorySettings
    # Here I use hard coded values but they should be in a class constants
    arguments:
      - !php/const \PrestaShopBundle\Service\DataProvider\Admin\NewsProvider::CLOSED_ALLOWED_FAILURES
      - !php/const \PrestaShopBundle\Service\DataProvider\Admin\NewsProvider::CLOSED_TIMEOUT_SECONDS
      - 0
    calls:
      - ['setThreshold', [!php/const \PrestaShopBundle\Service\DataProvider\Admin\NewsProvider::OPEN_THRESHOLD_SECONDS]]
      - ['setStrippedFailures', [!php/const \PrestaShopBundle\Service\DataProvider\Admin\NewsProvider::OPEN_ALLOWED_FAILURES]]
      - ['setStrippedTimeout', [!php/const \PrestaShopBundle\Service\DataProvider\Admin\NewsProvider::OPEN_TIMEOUT_SECONDS]]
      - ['setStorage', ['@prestashop.core.circuit_breaker.storage']]
      - ['setClientOptions', [{'method': 'GET', 'subscribers': ['@prestashop.core.circuit_breaker.guzzle.cache_subscriber']}]]

  prestashop.core.news.circuit_breaker:
    class: 'PrestaShop\CircuitBreaker\Contract\CircuitBreakerInterface'
    factory: ["@prestashop.core.circuit_breaker.advanced_factory", create]
    arguments:
      - "@prestashop.core.news.circuit_breaker.settings"

  prestashop.core.news.provider:
    class: PrestaShopBundle\Service\DataProvider\Admin\NewsProvider
    arguments:
      - "@prestashop.core.news.circuit_breaker"
      - "@prestashop.adapter.data_provider.country"
      - "@prestashop.adapter.tools"
      - "@prestashop.adapter.legacy.configuration"
      - "@prestashop.adapter.validate"
      - "@=service('prestashop.adapter.legacy.context').getContext().mode"