admin_theme_catalog:
    path: /addons-store
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\TheAdmin\Improve\Design\ThemeCatalogController:index'
        _legacy_controller: AdminThemesCatalog
