admin_order_delivery_slip:
    path: /delivery/slip
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Order/Delivery:slip
        _legacy_controller: AdminDeliverySlip
