services:
    _defaults:
        public: true

    prestashop.adapter.hook.command_handler.update_hook_status_handler:
        class: PrestaShop\PrestaShop\Adapter\Hook\CommandHandler\UpdateHooktatusCommandHandler
        tags:
          - name: tactician.handler
            command: PrestaShop\PrestaShop\Core\Domain\Hook\Command\UpdateHookStatusCommand

    prestashop.adapter.hook.command_handler.get_hook_status_handler:
        class: PrestaShop\PrestaShop\Adapter\Hook\QueryHandler\GetHookStatusdHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\Hook\Query\GetHookStatus
