services:
    _defaults:
        public: true

    # KPI implementations
    prestashop.adapter.kpi.enabled_languages:
        class: PrestaShop\PrestaShop\Adapter\Kpi\EnabledLanguagesKpi
        arguments:
            - '@prestashop.adapter.legacy.context'
            - '@translator'
            - '@prestashop.adapter.legacy.kpi_configuration'
            - '@prestashop.smarty'

    prestashop.adapter.kpi.main_country:
        class: PrestaShop\PrestaShop\Adapter\Kpi\MainCountryKpi
        arguments:
            - '@prestashop.adapter.legacy.context'
            - '@translator'
            - '@prestashop.adapter.legacy.kpi_configuration'

    prestashop.adapter.kpi.translations:
        class: PrestaShop\PrestaShop\Adapter\Kpi\TranslationsKpi
        arguments:
            - '@prestashop.adapter.legacy.context'
            - '@translator'
            - '@prestashop.adapter.legacy.kpi_configuration'
