services:
  _defaults:
    public: true

  prestashop.adapter.language.pack.importer:
    class: 'PrestaShop\PrestaShop\Adapter\Language\Pack\LanguagePackImporter'
    arguments:
      - '@prestashop.adapter.language.language_pack_installer'
      - '@prestashop.adapter.data_provider.language'
      - '@prestashop.core.cache.clearer.entire_cache_clearer'
      - '@=service("prestashop.adapter.legacy.configuration").get("_PS_TRANSLATIONS_DIR_")'
