services:
  _defaults:
    public: true

  prestashop.adapter.tax.ecotax.ecotax_resetter:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\Ecotax\ProductEcotaxResetter'
    _defaults:
      public: true

    # Command handlers

  prestashop.adapter.tax.command_handler.delete_tax_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\DeleteTaxHandler'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Tax\Command\DeleteTaxCommand' }
