services:
#  @deprecated - dont call repositories directly, use interface instead
  Mollie\Repository\PaymentMethodRepository:

  Mollie\Repository\PaymentMethodRepositoryInterface: '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Repository\OrderFeeRepository:

  Mollie\Repository\CountryRepository:

  Mollie\Repository\OrderShipmentRepository:

  Mollie\Repository\MethodCountryRepository:

  Mollie\Repository\MolCarrierInformationRepository:

  Mollie\Repository\ModuleRepository:

  Mollie\Repository\PendingOrderCartRepository:
    arguments:
      - 'MolPendingOrderCart'

  Mollie\Repository\MolCustomerRepository:
    arguments:
      - 'MolCustomer'

  Mollie\Repository\AttributeRepository:

  Mollie\Repository\OrderStateRepository:

  Mollie\Repository\OrderRepository:
    class: Mollie\Repository\OrderRepository

  Mollie\Repository\OrderCartRuleRepository:
    class: Mollie\Repository\OrderCartRuleRepository

  Mollie\Repository\CartRuleRepository:
    class: Mollie\Repository\CartRuleRepository

  Mollie\Repository\PendingOrderCartRuleRepository:
    class: Mollie\Repository\PendingOrderCartRuleRepository

  Mollie\Repository\MolPaymentMethodOrderTotalRestrictionRepository:
    class: Mollie\Repository\MolPaymentMethodOrderTotalRestrictionRepository

  Mollie\Repository\MolPaymentMethodOrderTotalRestrictionRepositoryInterface: '@Mollie\Repository\MolPaymentMethodOrderTotalRestrictionRepository'

  Mollie\Repository\CurrencyRepository:
    class: Mollie\Repository\CurrencyRepository

  Mollie\Repository\CurrencyRepositoryInterface: '@Mollie\Repository\CurrencyRepository'