imports:
    - { resource: admin/services.yml }

services:
    # ADAPTERS (prestashop.adapter.*)
    # Legacy context service, transitional
    prestashop.adapter.legacy.context:
        class: PrestaShop\PrestaShop\Adapter\LegacyContext

    # Legacy context service, transitional
    prestashop.adapter.translator:
        class: PrestaShop\PrestaShop\Adapter\Translator
        arguments: ["@prestashop.adapter.legacy.context"]

    # Data providers service
    prestashop.adapter.data_provider.supplier:
        class: PrestaShop\PrestaShop\Adapter\Supplier\SupplierDataProvider

    prestashop.adapter.data_provider.category:
        class: PrestaShop\PrestaShop\Adapter\Category\CategoryDataProvider

    prestashop.adapter.data_provider.tax:
        class: PrestaShop\PrestaShop\Adapter\Tax\TaxRuleDataProvider

    prestashop.adapter.data_provider.manufacturer:
        class: PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerDataProvider

    prestashop.adapter.data_provider.product:
        class: PrestaShop\PrestaShop\Adapter\Product\ProductDataProvider

    prestashop.adapter.shop.context:
        class: PrestaShop\PrestaShop\Adapter\Shop\Context

    prestashop.adapter.tools:
        class: PrestaShop\PrestaShop\Adapter\Tools

    # Adapter services that decorates interfaced services
    prestashop.adapter.admin.page_preference:
        class: PrestaShop\PrestaShop\Adapter\Admin\PagePreference
        decorates: prestashop.core.admin.page_preference_interface
        public: false

    #TWIG EXTENSIONS
    prestashop.twig.extension.translation:
        class: PrestaShopBundle\Twig\TranslationExtension
        arguments: ["@translator", "@prestashop.adapter.translator", "@service_container"]
        tags:
            - { name: twig.extension }

    prestashop.twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    prestashop.twig.extension.layout:
        class: PrestaShopBundle\Twig\LayoutExtension
        arguments: ["@prestashop.adapter.legacy.context"]
        tags:
            - { name: twig.extension }





