version: "3"

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prestashop
    restart: always
  apache:
    container_name: prestashop
    image: "prestashop/prestashop:${PRESTASHOP_VERSION}"
    environment:
      PS_INSTALL_AUTO: 1
      DB_PASSWD: password
      DB_NAME: prestashop
      DB_SERVER: mysql
      PS_DOMAIN: "localhost:${PRESTASHOP_PORT}"
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      ADMIN_MAIL: "prestashop@mollie.com"
      ADMIN_PASSWD: "mollie_test_156"
    ports:
      - "${PRESTASHOP_PORT}:80"
    volumes:
      - ./prestashop:/var/www/html/:delegated
    restart: always
