<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO0Xw5n8\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO0Xw5n8/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO0Xw5n8.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO0Xw5n8\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerO0Xw5n8\appAppKernelDevDebugContainer([
    'container.build_hash' => 'O0Xw5n8',
    'container.build_id' => 'a7339271',
    'container.build_time' => 1742300420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO0Xw5n8');
