name: Link checker

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build prestashop app
        run: cd ./tests/puppeteer/ && docker-compose -f docker-compose.nightly.yml -f docker-compose.tests.yml up -d --build --force-recreat
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Wait for prestashop to be available
        run: cd ./tests/puppeteer/ && docker-compose -f docker-compose.nightly.yml -f docker-compose.tests.yml exec -T tests /tmp/wait-for-it.sh --timeout=720 --strict prestashop-web:80
      - name: Disable token
        run: cd ./tests/puppeteer/ && docker-compose -f docker-compose.nightly.yml -f docker-compose.tests.yml exec -T prestashop sh -c 'echo "SetEnv _TOKEN_ disabled"  >> /var/www/html/admin-dev/.htaccess'
      - name: Launch link checker tests
        run: cd ./tests/puppeteer/ && docker-compose -f docker-compose.nightly.yml -f docker-compose.tests.yml exec -T -e COMMAND="linkchecker" tests bash /tmp/run-tests.sh
