name: Pull Request Validator

on: pull_request

jobs:
  message-check:
    if: "!contains(github.event.pull_request.title, '[merge]')"
    name: Block Merge Commits

    runs-on: ubuntu-latest

    steps:
      - name: Block Merge Commits
        uses: z3by/block-merge-commits-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.event.pull_request.title }}